version: '3.2'
services:
  nomad-worker:
    image: jmcarbo/nomad
    command: agent -client 
    depends_on:
      - nomad
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $PWD/nomad-config:/etc/nomad
    networks:
      - consul-net
    deploy:
        replicas: 3
        resources:
            reservations:
                memory: 128M
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
        update_config:
            parallelism: 1
            delay: 10s
            failure_action: continue

networks:
  consul-net:
    external: true

